version: '3'

# volumes:
#   db-data:
#     driver: local
#     driver_opts:
#       type: "nfs"
#       o: "addr=127.0.0.1,nolock,soft,rw"
#       device: ":/CS300-Data"

services:

  default-clinicaldata:
    restart: always
    build: .
    image: default-clinicaldata
    command: ["gunicorn", "-b", "127.0.0.1:8000", "--worker-class", "gthread", "-w", "1", "--threads", "1", "app:app"]
    expose: 
      - 8000
      - 443
    network_mode: "host"

  server:
    restart: always
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - default-clinicaldata
    # links:
    #   - default-clinicaldata:default-clinicaldata
    ports:
      - "80:80"
    network_mode: "host"